<?php
namespace  Home\Controller;
use Think\Model;

class GreenPanterController extends CommonController
{
    protected $panters;
    protected $parent;
    protected $panter_terminals;
    protected $zz_config;
    protected $pos;
    protected $model;
    protected $chongPanterid;//充值端id
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->panters          = M('panters');
        $this->panter_terminals = M('panter_terminals');
        $this->zz_config        = M('zz_config');
        $this->pos              = M('zz_pos');
        $this->model            = new Model();
        $this->parent           = '00000013';
        $this->chongPanterid    = '00000126';
    }
    public function index(){
        $map=['parent'=>$this->parent,'flag'=>'3','revorkflg'=>'N'];
        $map['panterid']=['neq',$this->chongPanterid];
       if($this->isGet($_GET)){
           $get = $_GET;
           $where=function() use ($get,$map){
               foreach($get as $key =>$val){
                     if($val){
                         $map[$key] = ['like','%'.$val.'%'];
                         $this->assign($key,$val);
                     }
               }
               return $map;
           };
           $this->getSimplePage($where(),$this->panters,'panterid');
       }else{
           $this->getSimplePage($map,$this->panters,'panterid');
       }
        $this->display();
    }
    public function addPanters(){
        if(IS_POST){
            $notice = ['namechinese'=>'商户名','address'=>'商户地址',
                       'conperbpno'=>'身份证号','period'=>'身份证有效期',
                       'conpername'=>'联系人'  ,'conperteleno'=>'联系人电话'
                      ];
            foreach($_POST as $key=>$val){
                if(isset($notice[$key])){
                    if(!$val){
                        $this->error($notice[$key].'不能为空');
                    }
                    $add[$key] = trim($val);
                }
            }
            $panterid  = $this->getFieldNextNumber('panterid');
            if(strlen($panterid)<8){
                $i = strlen($panterid);
                for($i;$i<8;$i++){
                    $panterid ='0'.$panterid;
                }
            }
            $placeddate = date('Ymd',time());
            $sql ="insert into panters (panterid,namechinese,address,conperbpno,period,conpername,conperteleno,revorkflg,parent,accounttype,status,flag,placeddate,nameenglish) VALUES (";
            $sql.="'{$panterid}','{$add['namechinese']}','{$add['address']}','{$add['conperbpno']}','{$add['period']}','{$add['conpername']}','{$add['conperteleno']}'";
            $sql.=",'N','{$this->parent}','Z','1','3','{$placeddate}','{$add['nameenglish']}')";
            $boolAdd=$this->panters->execute($sql);
            if($boolAdd){
                $this->success('新增商户成功','index');
            }else{
                $this->error('新增商户失败');
            }
        }
        $this->display();
    }
    //商户编辑
    public function editPanter(){
        if(IS_POST){
            $notice = ['namechinese'=>'商户名','address'=>'商户地址',
                'conperbpno'=>'身份证号','period'=>'身份证有效期',
                'conpername'=>'联系人'  ,'conperteleno'=>'联系人电话'
            ];
            foreach($_POST as $key=>$val){
                if(isset($notice[$key])){
                    $edit[$key] = trim(I("post.$key",''));
                    if(!$edit[$key]){
                        $this->error($notice[$key].'不能为空');
                    }
                }
                $panterid = trim(I('post.panterid',''));
                $edit['nameenglish'] = trim(I('post.nameenglish',''));
                $this->getCheckPanterid($panterid);
                $editif=$this->panters->where(['panterid'=>$panterid])->save($edit);
                if($editif){
                    $this->success('修改商户成功','index');
                }else{
                    $this->error('修改商户失败，请重试！');
                }
            }
        }else{
            $panterid = trim(I('get.panterid',''));
            $this->getCheckPanterid($panterid);
            $list  = $this->panters->where(['panterid'=>$panterid])->find();
            $this->assign('list',$list);
            $this->display();
        }

    }
    //新增终端
    public function addTerminal(){
        if(IS_POST){
            $notice = ['panterid'=>'商户id','ip'=>'ip编号',
                'flag'=>'终端标识符','description'=>'描述',
            ];
           foreach($_POST as $key =>$val){
               $add[$key] = trim(I("post.$key",''));
               if($add[$key]==''){
                   $this->error($notice[$key].'不能为空');
               }
           }
           $id=$this->getnextcode('terminals',8);
           $terminalid=substr($add['panterid'],5,3).substr($id,3,5);
           $sql = "insert into panter_terminals(panterid,ip,description,flag,bind,terminal_id) VALUES (";
           $sql.= "'{$add['panterid']}','{$add['ip']}','{$add['description']}','{$add['flag']}','N','{$terminalid}')";
           if($this->model->execute($sql)){
               $this->success('新增终端成功',U('GreenPanter/indexTerminal',['panterid'=>$add['panterid']]));
           }else{
               $this->error('新增终端失败,请重试!');
           }
        }else{
            $panterid = trim(I('get.panterid',''));
            $this->getCheckPanterid($panterid);
            $this->display();
        }
    }
    //编辑终端
    public function editTerminal(){
        if(IS_POST){
            $notice = ['terminal_id'=>'终端号','ip'=>'ip编号',
                'flag'=>'终端标识符','description'=>'描述',
            ];
            foreach($_POST as $key =>$val){
                $edit[$key] = trim(I("post.$key",''));
                if($edit[$key]==''){
                    $this->error($notice[$key].'不能为空');
                }
            }
            $panterid = trim(I('post.panterid',''));
            $editMap=['ip'=>$edit['ip'],'flag'=>$edit['flag'],'description'=>$edit['description']];
            if($this->panter_terminals->where(['terminal_id'=>$edit['terminal_id']])->save($editMap)){
                $this->success('修改终端成功',U('GreenPanter/indexTerminal',['panterid'=>$panterid]));
            }else{
                $this->error('新增终端失败,请重试!');
            }
        }else{
            $terminal_id = trim(I('get.terminal_id',''));
            $list = $this->panter_terminals->where(['terminal_id'=>$terminal_id])->find();
            $this->assign('list',$list);
            $this->display();
        }
    }

    //终端展示主页
    public function indexTerminal(){
        $panterid = trim(I('get.panterid',''));
        $this->getCheckPanterid($panterid);
        $map['panterid'] = $panterid;
        $this->getSimplePage($map,$this->panter_terminals,'terminal_id');
        $this->display();
    }
    /*
     * 绑定旧机具
     */
    public function posConfig(){
        $terminal = trim(I('get.terminal',''));
        if($terminal==''){
            $this->error('非法参数传入',U('GreenPanter/index'));
        }else{
            $this->assign('terminal',$terminal);
        }
        $imeis = $this->imeiForbid();
        $this->assign('imeis',$imeis);
        $this->display();
    }
    /*
     * 绑定旧机具实现
     */
    public function bindOldImei(){
        if(IS_POST){
            $notice = ['pos_id'=>'设备描述','imei'=>'imei',
                      'terminal'=>'终端号'
            ];
            foreach($notice as $key => $val){
                $bind[$key] = trim(I("post.{$key}",''));
                if($bind[$key]==''){
                    $this->error($val.'不能为空',U('GreenPanter/posConfig',['terminal'=>trim($_POST['terminal'])]));
                }
            }
            $panterid =  $this->terminalPanterid($bind['terminal']);
            if($panterid){
                $this->model->startTrans();
                //zz_pos 更换 设备id 即pos 描述
               $posif = $this->savePosID($bind['pos_id'],$bind['imei']);
               //zz_config 配置修改
                $configif = $this->saveConfigPanter($bind['imei'],$panterid,$bind['terminal'],$bind['pos_id']);
                //修改panter_terminal 为绑定
                $bindTerminalif = $this->editTerminalStatus($bind['terminal'],'Y');
                if($posif==true && $configif==true && $bindTerminalif==true){
                   $this->model->commit();
                   $this->success('绑定终端成功',U('GreenPanter/indexTerminal',['panterid'=>$panterid]));
                }else{
                    $this->model->rollback();
                    $this->error('绑定终端失败,请重试',U('GreenPanter/posConfig',['terminal'=>trim($_POST['terminal'])]));
                }

            }else{
                $this->error('此终端号异常',U('GreenPanter/index'));
            }
        }
    }
    /*
     * 绑定新机具
     */
    public function addPos(){
        if(IS_POST){
            $notice = ['pos_id'=>'设备描述','imei'=>'imei',
                       'terminal'=>'终端号','consignee'=>'录入人员'
            ];
            foreach($notice as $key => $val){
                $bind[$key] = trim(I("post.{$key}",''));
                if($bind[$key]==''){
                    $this->error($val.'不能为空',U('GreenPanter/addPos',['terminal'=>trim($_POST['terminal'])]));
                }
            }
            $arr = $this->imeiUnique($bind['imei']);
            if($arr['status']!=1){
                $this->error($arr['codemsg'],U('GreenPanter/addPos',['terminal'=>trim($_POST['terminal'])]));
            }
            $panterid =  $this->terminalPanterid($bind['terminal']);
            if($panterid){
                $this->model->startTrans();
                //新增pos
                $aid = $this->getnextcode("zz_pos",11);
                $posif = $this->addPosId($aid,$bind['pos_id'],$bind['imei'],$bind['consignee']);
                //zz_config 配置添加
                $configif = $this->addConfigPanter($aid,$bind['pos_id'],$bind['imei'],$bind['terminal'],$panterid);
                //修改panter_terminal 为绑定
                $terminalif = $this->editTerminalStatus($bind['terminal'],'Y');
                if($posif==true && $configif==true && $terminalif==true){
                    $this->model->commit();
                    $this->success('新增绑定终端成功',U('GreenPanter/indexTerminal',['panterid'=>$panterid]));
                }else{
                    $this->model->rollback();
                    $this->error('绑定终端失败,请重试',U('GreenPanter/addPos',['terminal'=>trim($_POST['terminal'])]));
                }

            }else{
                $this->error('此终端号异常',U('GreenPanter/index'));
            }

        }else{
            $terminal = trim(I('get.terminal',''));
            if($terminal==''){
                $this->error('非法参数传入',U('GreenPanter/index'));
            }else{
                $this->assign('terminal',$terminal);
            }
            $this->display();
        }
    }
    public function indexPos(){
        $panterArr = $this->getImeiPanterid($this->parent);
        $map['panterid'] = ['in',$panterArr];
        $map['payid']    = '02';
        if($this->isGet($_GET)){
            $get = $_GET;
            $where = function () use ($get,$map){
                foreach($get as $key=>$val){
                    if($val){
                        $map[$key] = ['like','%'.$val.'%'];
                        $this->assign($key,$val);
                    }
                }
                return $map;
            };
            $this->getSimplePage($where(),$this->zz_config,'aid');
        }else{
            $this->getSimplePage($map,$this->zz_config,'aid');
        }
        $this->display();
    }
    //禁用 pos配置
    public function forbidConfig(){
        if(IS_POST){
            $imei = I('post.imei','');
            if($imei==''){
                returnMsg(['status'=>'4','codemsg'=>'imei非法传入']);
            }
            if($this->editConfigStatus($imei,'1')){
                returnMsg(['status'=>'1','codemsg'=>'禁用成功']);
            }else{
                returnMsg(['status'=>'3','codemsg'=>'数据库操作失败,请重试']);
            }
        }else{
            returnMsg(['status'=>'2','codemsg'=>'非法传入']);
        }
    }
   //开启pos配置
    public function startConfig(){
        if(IS_POST){
            $imei = I('post.imei','');
            if($imei==''){
                returnMsg(['status'=>'4','codemsg'=>'imei非法传入']);
            }
            if($this->editConfigStatus($imei,'0')){
                returnMsg(['status'=>'1','codemsg'=>'解禁成功']);
            }else{
                returnMsg(['status'=>'3','codemsg'=>'数据库操作失败,请重试']);
            }
        }else{
            returnMsg(['status'=>'2','codemsg'=>'非法传入']);
        }
    }
    /*-----------------------------------------------分界线-----------------------------------------------------------*/
    /*
     * addPos 前台imei ajax验证
     */
    public function checkImei(){
        $imei = trim(I('post.imei',''));
        if($imei==''){
            returnMsg(['status'=>'4','codemsg'=>'imei不能为空!']);
        }else{
            returnMsg($this->imeiUnique($imei));
        }
    }
    /*
     * 简单分页实现 单表查询  倒叙拍板
     * @param array $where 查询条件
     * @param obj   $obj
     */
    protected function getSimplePage($where,$obj,$order){
        $count = $obj->where($where)->count();
        $p=new \Think\Page($count, 10);
        $lists=$obj->where($where)->order("$order  desc")->limit($p->firstRow.','.$p->listRows)->select();
        $page = $p->show();
        $this->assign('count',$count);
        $this->assign('page',$page);
        $this->assign('lists',$lists);
    }
    /*
     * 检查get方式是否有值传入
     */
    protected function isGet($get){
        $bool = false;
        foreach($get as $k =>$v){
             if($v){
                 $bool = true;
                 break;
             }
        }
        return $bool;
    }
    /*
     * get方式获取panterid 的检验
     * @param string $panterid
     */
    protected function getCheckPanterid($panterid){
        if($panterid!=''){
            $this->assign('panterid',$panterid);
        }else{
            $this->error('非法参数传入',U('GreenPanter/index'));
        }
    }
    /*
     * 获取pos配置中被禁用的imei
     * 只查询至尊卡 的配置
     */
    protected function imeiForbid(){
        $panters  = $this->zz_config->where('forbid = 1')->select();
        $panterArr= $this->getParentPanterid($this->parent);
        if($panters){
            $list = array_unique(array_column($panters,'panterid'));
            foreach($list as $key => $val){
                $realPanterid =substr($val,-8);
                if(array_search($realPanterid,$panterArr)){
                    $wherePanter[] = $val;
                }
            }
            if($wherePanter){
                $where['forbid'] = '1';
                $where['panterid'] = ['in',$wherePanter];
                $where['payid']  = '02';
                return array_combine(array_column($this->zz_config->where($where)->order('aid desc')->select(),'imei'),
                    array_column($this->zz_config->where($where)->order('aid desc')->select(),'namechinese'));
            }else{
                return false;
            }
        }else{
            return false;
        }
    }
    /*
     * 获取某机构下所有商户id
     * @param  string $parent 机构号（另外去除 充值端的 商户号）
     */
    protected function getParentPanterid($parent){
        $map['parent'] = $parent;
        $map['flag']   = '3';
        $map['revorkflg']='N';
        return $this->exceptChongPanterid(array_column($this->panters->where($map)->select(),'panterid'));
    }
    /*
     * 查询某个终端所属商户号
     */
    protected function terminalPanterid($terminal){
       $list = $this->panter_terminals->where(['terminal_id'=>$terminal,'flag'=>'Y'])->field('panterid')->find();
       if($list){
           return $list['panterid'];
       }else{
           return false;
       }
    }
    /*
     * 更新zz_pos设备id
     * @param string $pos_id 设备id 即pos设备描述
     * @param sting $imei imei号
     */
    protected function savePosID($pos_id,$imei){
        return $this->pos->where(['imei'=>$imei])->save(['pos_id'=>$pos_id]);
    }
    /*
     * 更新zz_config panterid 以及商户名 即商户信息 以及pos终端 移除原有终端绑定
     * @param sting $imei imei号
     * @param sting $panterid 商户号
     * @param sting $terminal 终端号
     * @param string $pos_id 设备id 即pos设备描述
     */
    protected function saveConfigPanter($imei,$panterid,$terminal,$pos_id){
        //查询原来终端
        $list= $this->zz_config->where(['imei'=>$imei])->field('pos_id')->find();
        $terminalif = $this->editTerminalStatus($list['pos_id'],'N');
        $new['panterid'] = $panterid;
        $new['pos_id']   = $terminal;
        $new['namechinese']=$pos_id;
        $new['forbid']     ='0';
        $bindif=$this->zz_config->where(['imei'=>$imei])
                      ->save($new);
        if($terminalif==true && $bindif==true){
            return true;
        }else{
            return false;
        }
    }
    /*
     * 修改panter_terminals 绑定状态
     * @param  string  $termnal 终端号
     * @parma  string  $type  类型  Y绑定 N未绑定
     */
    protected function editTerminalStatus($terminal,$type){
        return $this->panter_terminals->where(['terminal_id'=>$terminal])->save(['bind'=>$type]);
    }
    /*
     * 新增绑定 imei 的唯一性检验
     * @param sting $imei imei号
     */
    protected function imeiUnique($imei)
    {
        $where['imei'] = $imei;
        if($this->pos->where($where)->find())
        {
            $arr['status'] = 2;
            $arr['codemsg'] = "此imei已经绑定,请更换!";
            return $arr;
        }else{
            return ['status'=>'1','codemsg'=>'此imei可用'];
        }
    }
    /*
     * 新增pos
     */
    protected function addPosId($aid,$pos_id,$imei,$consignee){
        $time= date('Ymd',time());
        $slq = "insert into zz_pos(aid,pos_id,imei,consignee,add_time) VALUES (";
        $slq.= "'{$aid}','{$pos_id}','{$imei}','{$consignee}','{$time}')";
        return $this->model->execute($slq);
    }
    /*
     * 新增pos配置
     */
    protected function addConfigPanter($aid,$pos_id,$imei,$terminal,$panterid){
        $payid = '02';
        $sql = "insert into zz_config (aid,pos_id,num_id,ip_address,payid,status,panterid,namechinese,imei,forbid) VALUES (";
        $sql.= "'{$aid}','{$terminal}','8090','127.0.0.1','{$payid}','1','{$panterid}','{$pos_id}','{$imei}','0')";
        return $this->model->execute($sql);
    }
    /*
     * 查询某个机构所有商户配置下的所有imei 对应的商户号
     */
    protected function getImeiPanterid($parent){
        $arr = $this->zz_config->where(['payid'=>'02'])->select();
        $panterArr= $this->getParentPanterid($this->parent);
        $list = array_unique(array_column($arr,'panterid'));
        foreach($list as $key => $val){
            $realPanterid =substr($val,-8);
            if(array_search($realPanterid,$panterArr)){
                $wherePanter[] = $val;
            }
        }
        return $wherePanter;
    }
    /*
     * pos配置 payid=2 的禁用 或者开启
     */
    protected function editConfigStatus($imei,$type){
       return  $this->zz_config->where(['imei'=>$imei,'payid'=>'02'])->save(['forbid'=>$type]);
    }
    /*
     * 商户名唯一性 检验
     */
    public function panterName(){
        $where['namechinese'] = trim($_POST['namechinese']);
        $panterid = trim(I('post.panterid',''));
        if($panterid!=''){
            $where['panterid'] = ['neq',$panterid];
        }
        $data['status']=0;
        $data['name']="";
        if($this->panters->where($where)->find())
        {
            $data['status'] = 1;
            $data['name'] = "商户名已存在";
        }
        echo json_encode($data);
    }
    /*
     * 返回某机构所有商户时候剔除 充值端商户
     */
    protected function exceptChongPanterid($panterArr){
        $bool = array_search($this->chongPanterid,$panterArr);
        if($bool===false){
            return $panterArr;
        }else{
            unset($panterArr[$bool]);
            return $panterArr;
        }
    }

}