<?php
namespace Home\Controller;

class ShowlogController extends CommonController{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    //查看系统操作日志
    public function index(){
        $model = M('operator_logs');
        $where = "a.placedate>20170101";
        $count = $model->alias('a')->where($where)->count();
        $this->assign('count',$count);
        $p = new \Think\Page($count, 10 );
        $data = $model->alias('a')
            ->join('users b on a.userid=b.userid')
            ->field('a.logintime placedate,a.logouttime placetime,
                     a.loginip,a.formname,b.loginname')
            ->limit($p->firstRow.','.$p->listRows)
            ->where($where)
            ->order("a.operatorlogid desc")
            ->select();
        foreach ($data as $k => $v) {
            $list[$k]  =  $v;
            $list[$k]['placeddate'] = date('Y-m-d H:s:i',strtotime($v['placedate'].$v['placetime']));

        }

        $page = $p->show();
        $this->assign('list',$list);
        $this->assign('page',$page);
        $this->display();

    }
}